### PR TITLE
CP of 95b62f69f668f8c3baf7f5f1ea8bd2f13d77a16a (PR#3711) from Develop to Main, to fix PostBuild event

### PR DESCRIPTION
**Pull request by alexlamtest**
Revert back to before commit 3fae06d7e5a9083f5d50d99305efe0afc1edbc35…
… [Fix PostBuild event for copying Bootstrap DLL (#3683)] (#3711)

--

A microsoft employee must use /azp run to validate using the pipelines below.

WARNING:
Comments made by azure-pipelines bot maybe inaccurate. 
Please see pipeline link to verify that the build is being ran.

For status checks on the develop branch, please use TransportPackage-Foundation-PR
(https://microsoft.visualstudio.com/ProjectReunion/_build?definitionId=81063&_a=summary)
and run the build against your PR branch with the default parameters.

For status checks on the main branch, please use microsoft.ProjectReunion
(https://dev.azure.com/ms/ProjectReunion/_build?definitionId=391&_a=summary)
and run the build against your PR branch with the default parameters.

### CODE REVIEW

**Review by evelynwu-msft — APPROVED** [review]

**Review by codendone — APPROVED** [review]
:shipit:

**Comment by alexlamtest** [comment]
Not needed any more.

**Comment by alexlamtest** [comment]
I think we don't need this any more

**Pull request closed without merging**
