### PR TITLE
Try adding push notification unit tests to Helix

### PR DESCRIPTION
**Pull request by loneursid**

### CODE REVIEW

**Comment by danielayala94** [comment]
Can you tell me what is the difference between #2146 and this PR? I know the changes are different, but both are suggesting onboarding the push notification tests into Helix 😊

**Comment by loneursid** [comment]
@danielayala94 - They're just different experiment based on work done by Howard and Jeff Genovy. They're all experiments and not intended to be merged anytime soon. They need to be open as PR (even draft) as it's the only way to run the pipelines.

**Pull request closed without merging**
