### PR TITLE
Added renames from Windows -> WindowsApp

### PR DESCRIPTION
**Pull request by pmpurifoy**
Renaming Windows namespace to WindowsApp.

### CODE REVIEW

**Comment by danielayala94** [comment]
Did you run the TAEF tests and the demo app as part of this change?

**Comment by pmpurifoy** [comment]
> Did you run the TAEF tests and the demo app as part of this change?

Yes. All tests passed with the namespace changes.

**Review by danielayala94 — APPROVED** [review]

**Review by sharath2727 — APPROVED** [review]

**Comment by DrusTheAxe** [comment]
You'll want to hold off completion until you hear the latest guidance

**Review by DrusTheAxe — CHANGES_REQUESTED** [review]
Wait for latest guidance

**Comment by pmpurifoy** [comment]
Guidance was to leave as Windows.

**Pull request closed without merging**
