### PR TITLE
Do not add xbf files to UpToDateCheckInput as they are output files.

### PR DESCRIPTION
**Pull request by jlaanstra**
Fixes ADO#43580700. We've tested this fix for the last two weeks inside Phone Link and have seen significant improvements in inner dev loop for xaml files and observed no other issues with this. /cc @bpulliam 

A microsoft employee must use /azp run to validate using the pipelines below.

WARNING:
Comments made by azure-pipelines bot maybe inaccurate. 
Please see pipeline link to verify that the build is being ran.

For status checks on the develop branch, please use TransportPackage-Foundation-PR
(https://microsoft.visualstudio.com/ProjectReunion/_build?definitionId=81063&_a=summary)
and run the build against your PR branch with the default parameters.

For status checks on the main branch, please use microsoft.ProjectReunion
(https://dev.azure.com/ms/ProjectReunion/_build?definitionId=391&_a=summary)
and run the build against your PR branch with the default parameters.

### CODE REVIEW

**Comment by jlaanstra** [comment]
@bpulliam buildfailure doesn't look related to this change?

**Comment by Scottj1s** [comment]
Hmm, build log says "StageAndPack was canceled"

/azp run

**Comment by Scottj1s** [comment]
@rohanp-msft any concerns here?

**Comment by rohanp-msft** [comment]
I think the change itself is fine. I'm thinking about the duplicate logic in `_GenerateProjectPriConfigurationFiles`. I'll reply soon for that. Also, FYI @loneursid (ownership of MRT has been transferred).

---
In reply to: [1480287836](https://github.com/microsoft/WindowsAppSDK/pull/3522#issuecomment-1480287836) [](http://example.com/codeflow?ancestors=1480287836,1480287836)

**Comment by jlaanstra** [comment]
> I think the change itself is fine. I'm thinking about the duplicate logic in `_GenerateProjectPriConfigurationFiles`. I'll reply soon for that. Also, since ownership of MRT has been transferred, FYI @loneursid.
> 
> In reply to: [1480287836](https://github.com/microsoft/WindowsAppSDK/pull/3522#issuecomment-1480287836)

You still want to reference the xbf for the pri file I think?

**Comment by rohanp-msft** [comment]
> > I think the change itself is fine. I'm thinking about the duplicate logic in `_GenerateProjectPriConfigurationFiles`. I'll reply soon for that. Also, since ownership of MRT has been transferred, FYI @loneursid.
> > In reply to: [1480287836](https://github.com/microsoft/WindowsAppSDK/pull/3522#issuecomment-1480287836)
> 
> You still want to reference the xbf for the pri file I think?

Yeah. I think we should keep _GenerateProjectPriConfigurationFiles as is.

**Comment by rohanp-msft** [comment]
@jlaanstra Any thoughts on why there is perf improvement with this change? If there is a change in an XBF, I would think there would be a corresponding change in the corresponding XAML file. In that case, the incremental build behavior will be the same if we used XAML files instead of XBF files in `UpToDateCheckInput`.

**Comment by jlaanstra** [comment]
> @jlaanstra Any thoughts on why there is perf improvement with this change? If there is a change in an XBF, I would think there would be a corresponding change in the corresponding XAML file. In that case, the incremental build behavior will be the same if we used XAML files instead of XBF files in `UpToDateCheckInput`.

There is no perf improvements to a single build. However, without this change VS will always consider every subsequent build out of date as the xbf file was marked as an input file, but it was modified after the build started.

**Review by rohanp-msft — APPROVED** [review]
:shipit:

**Comment by jlaanstra** [comment]
@Scottj1s let's merge this?

**Review by Scottj1s — APPROVED** [review]

**Comment by rohanp-msft** [comment]
FYI @loneursid

**Pull request merged**
