### PR TITLE
Add DynamicDependencies' tests to the CI/PR/nightly/etc test runs

### PR DESCRIPTION
**Pull request by DrusTheAxe**

### CODE REVIEW

**Comment by pmpurifoy** [comment]
Make sure you publish your testdef to BuildOutput.

<Target Name="CopyFiles" AfterTargets="AfterBuild"> <Copy SourceFiles="DynamicDependencies_API_Win32.testdef" DestinationFolder="$(OutDir)" /> </Target>

**Comment by DrusTheAxe** [comment]
There's a test problem with some x86 tests (product seems fine, something about the tests/config/environment) so that's currently disabled.

**Review by alexlamtest — APPROVED** [review]
I like these 2 tests getting hooked up into the pipeline test environment, and they getting additional logging to aim troubleshooting.

**Pull request merged**
