### PR TITLE
[1.1][AppLifecycle] Properly ignore cleanup event if it can't be opened.

### PR DESCRIPTION
**Pull request by jlaanstra**
If we can't open the cleanup event, ignore it.

Fixes ADO#38606299

Cherry-picked from #2658

### CODE REVIEW

**Review by BenJKuhn — APPROVED** [review]

**Comment by BenJKuhn** [comment]
Please do not commit this PR until the 1.1.3 servicing update is published.

**Comment by jlaanstra** [comment]
@dhoehna can you kick off a build so we can merge this?

**Comment by MikeHillberg** [comment]
[Internal link](http://task.ms/40424043)

**Pull request merged**
