### PR TITLE
Remove [experimental] tags take 2 (#2306)

### PR DESCRIPTION
**Pull request by loneursid**
* removing experimental requires removing everything

* Code cleanup

Co-authored-by: Eric Langlois <erlangl@microsoft.com>

### CODE REVIEW

**Review by hulumane — APPROVED** [review]

**Review by jonwis — COMMENTED** [review]
Seems OK.  Is this the right time to also add the `[contract]` tagging?

**Comment by loneursid** [comment]
> Seems OK. Is this the right time to also add the [contract] tagging?

No! This is targeting the preview1 branch and still hasn't cleared shiproom. I don't we want to add contracts. We already have contracts for AppNotifications, I'm happy to create a separate PR to add contracts for PushNotifications but targeting main

**Review by kythant — APPROVED** [review]

**Pull request merged**
