### PR TITLE
Update roadmap.md

### PR DESCRIPTION
**Pull request by andrewleader**
Roadmap updates...

* Updating Self-contained to not be supported till future version
* Renamed "InApp" and "FxPackage" to "Self-contained" and "Framework-package" to match .NET terminology
* Added single-project MSIX to the packaged app roadmap
* Added elevation support to both roadmaps
* Added dynamic dependencies to both roadmaps

**Packaged apps**

Before | After
--|--
image | image

**Unpackaged apps**

Before | After
--|--
image | image

### CODE REVIEW

**Comment by riverar** [comment]
This PR changes the "in-app" support from experimental to not supported. 0.8 was already released, so this doesn't seem right.

The **previous roadmap** has the following:

> ### Packaged Desktop Apps
> 🌟 |    0.8    |       1.0 (Q4 2021)     |   Future release
> -- | ------------------------------- | --------------------------------- | ------------------------------- |
> • In-app | ✅ Supported | ✅ Supported | ✅ Supported |
> • Fx Package | ✅ Supported | ✅ Supported | ✅ Supported |
> 
> 
> ### Unpackaged Desktop Apps
> 🌟 |    0.8    |       1.0 (Q4 2021)     |   Future release
> -- | ---------------------------------- | ------------------------------ | ------------------------------- |
> • In-app | 🔄 Experimental | ✅ Supported | ✅ Supported |
> • Fx Package | 🔄 Experimental | ✅ Supported | ✅ Supported |


The proposed roadmap has the following:

> ### Packaged Desktop Apps
> 🌟 |    0.8    |       1.0 (Q4 2021)     |   Future release
> -- | ------------------------------- | --------------------------------- | ------------------------------- |
> • [Framework-dependent](https://docs.microsoft.com/windows/apps/windows-app-sdk/deploy-packaged-apps) | ✅ Supported | ✅ Supported | ✅ Supported |
> • [Self-contained](https://github.com/microsoft/WindowsAppSDK/issues/1204) | ❌ Not Supported | ❌ Not Supported | ✅ Supported |
> 
> 🌟 |    0.8    |       1.0 (Q4 2021)     |   Future release
> -- | ---------------------------------- | ------------------------------ | ------------------------------- |
> • [Framework-dependent](https://docs.microsoft.com/windows/apps/windows-app-sdk/deploy-unpackaged-apps) | ✅ Supported | ✅ Supported | ✅ Supported |
> • [Self-contained](https://github.com/microsoft/WindowsAppSDK/issues/1204) | ❌ Not Supported | ❌ Not Supported | ✅ Supported |

**Review by riverar — CHANGES_REQUESTED** [review]
Requested clarification.

**Comment by andrewleader** [comment]
@riverar 0.8 never included "in-app" support (even for experimental), neither did 0.5. We're updating the roadmap to reflect that this was never supported (the previous roadmap was incorrect).

**Comment by riverar** [comment]
@andrewleader I can accept that, but what about where 0.8 listed framework-dependent as experimental but is now "supported"? (Bootstrapping 0.8 apps was experimental.)

**Comment by andrewleader** [comment]
Ah whoops, that one was a mistake! Updating.

**Review by riverar — APPROVED** [review]

**Review by mshaikhcool — CHANGES_REQUESTED** [review]
* [WinUI 3](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md) - the Windows 10 native UI platform for Win32 and UWP

as per [WinUI community call](https://www.youtube.com/watch?v=9EOKxjFyY68&t=3052s) , WinUI 3 team has no plans to support UWP until further notice. UWP should be removed for the sake of clarity.

**Review by tfennel — APPROVED** [review]
Other than comments already left by others, looks accurate.

**Pull request merged**
