### PR TITLE
conditionally reference experimental metadata

### PR DESCRIPTION
**Pull request by Scottj1s**

### CODE REVIEW

**Comment by riverar** [comment]
Is there more context you can add here?

**Comment by Scottj1s** [comment]
@riverar this was experimental metadata that was removed for the 1.0 (non-experimental) release, but the references were not

**Comment by Scottj1s** [comment]
as a workaround:

>type Directory.Build.targets
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="RemoveExperimentalMetadataReferences" Outputs="@(Reference)" AfterTargets="ResolveReferences">
    <ItemGroup>
      <Reference Remove="@(Reference)" Condition="'%(Reference.Filename)%(Reference.Extension)' == 'Microsoft.Windows.System.winmd'" />
      <Reference Remove="@(Reference)" Condition="'%(Reference.Filename)%(Reference.Extension)' == 'Microsoft.Windows.PushNotifications.winmd'" />
    </ItemGroup>
  </Target>
</Project>

**Review by EHO-makai — COMMENTED** [review]
This looks fine to me.  Was there a pre-1.0 stable release PR that removed the experimental dependencies or are these new go-forward experimental references?

**Comment by Scottj1s** [comment]
> This looks fine to me. Was there a pre-1.0 stable release PR that removed the experimental dependencies or are these new go-forward experimental references?

As I understand from Ryan, this is a regression - the experimental metadata was removed, but not the dangling references.  I think making them conditional should support for release and experimental builds.

**Review by BenJKuhn — APPROVED** [review]

**Comment by Scottj1s** [comment]
haha, well okay, Ben!

**Comment by Scottj1s** [comment]
cherry pick to main:
https://github.com/microsoft/WindowsAppSDK/pull/1802

**Pull request merged**
