### PR TITLE
Update WinUI3 logo

### PR DESCRIPTION
**Pull request by Lamparter**
Hello!
This is a community follow-up PR to [microsoft/microsoft-ui-xaml#10189](https://github.com/microsoft/microsoft-ui-xaml/pull/10189) where the WinUI3 logo is being updated 🎉 
In this PR I've replaced the logo with the new one in all the places I could find (shoutout to @ghost1372 for helping me out) - please let me know if I've missed anywhere!

---
A microsoft employee must use /azp run to validate using the pipelines below.

WARNING:
Comments made by azure-pipelines bot maybe inaccurate.
Please see pipeline link to verify that the build is being ran.

For status checks on the main branch, please use TransportPackage-Foundation-PR
(https://microsoft.visualstudio.com/ProjectReunion/_build?definitionId=81063&_a=summary)
and run the build against your PR branch with the default parameters.

### CODE REVIEW

**Comment by ghost1372** [comment]
Thank you  @Lamparter  for you PR
But it is still not clear which icon was chosen for the template. Because we have a separate icon for WASDK
image

**Comment by Lamparter** [comment]
The app template is an app that uses WinUI3 (the design system) so I imagined that the logo should be the winui3 one and not the WinAppSDK one.

**Comment by Lamparter** [comment]
@ghost1372 do you know where else the logo might be?

**Comment by 0x5bfa** [comment]
What about NuGet's icon: https://www.nuget.org/packages/Microsoft.WindowsAppSdk/
It's currently Windows logo but should be the new one.

**Comment by ghost1372** [comment]
> What about NuGet's icon: https://www.nuget.org/packages/Microsoft.WindowsAppSdk/ It's currently Windows logo but should be the new one. I guess here? https://github.com/microsoft/WindowsAppSDK/tree/main/assets

yes final step is nuget package icon

**Comment by ghost1372** [comment]
> @ghost1372 do you know where else the logo might be?

i think nuget package should use wasdk icon

**Comment by niels9001** [comment]
Hey everyone! I love the initiative here and the effort you’ve put into it—it’s fantastic to see! We’ve also been exploring ways to enhance the iconography for project and item templates to make them more distinguishable and improve accessibility. I’ve created a tracking issue here: https://github.com/microsoft/WindowsAppSDK/issues/4923, and we’ll be submitting a PR with the new icons soon. Looking forward to collaborating on this!

**Comment by 0x5bfa** [comment]
I think this PR was superseded by #4924

**Comment by Lamparter** [comment]
@niels9001 would you like me to close this PR?

**Pull request closed without merging**
