### PR TITLE
Fixed a redundant error check in Test-PackageDependency.Tests.ps1

### PR DESCRIPTION
**Pull request by DrusTheAxe**

### CODE REVIEW

**Review by alexlamtest — COMMENTED** [review]
Thanks for fixing this instance.
Is the similar instance in Test-MsixDynamicDependency.Tests.ps1 being intentionally skipped?

**Comment by DrusTheAxe** [comment]
> Thanks for fixing this instance. Is the similar instance in Test-MsixDynamicDependency.Tests.ps1 being intentionally skipped?

Same redundancy. No surprise as the cmdlet tests were derived from the function tests.

Fixed to match

**Review by alexlamtest — APPROVED** [review]

**Pull request merged**
