### PR TITLE
UndockedRegFreeWinRT reentrancy bug

### PR DESCRIPTION
**Pull request by DrusTheAxe**
The UndockedRegFreeWinRT (URFW) support for the package graph deadlocks on `std::mutex` due to reentrancy.

Fixed by changing `std::mutex` to `std::recursive_mutex`.

[RoGetActivationFactoryDetour doesn't support reentrancy? #1277](https://github.com/microsoft/WindowsAppSDK/issues/1277)

NOTE: I've added tests to repro the issue but something's not not quite right about them as I can't reproduce the issue. But XAML has demonstrative proof via local testing the reentrancy issue is real _AND_ it's fixed by switching `mutex` to `recursive_mutex`. Visual inspection of the code verifies that. Rather than block critical path of folks awaiting this fix we'll go with the fix we know works and I'll follow up separate with the XAML folks to try to identify how to update the tests.

### CODE REVIEW

**Comment by DrusTheAxe** [comment]
`Sorry! Our services aren't available right now.`

Azure DevOps (Helix?) problem on the x86 run :-(

Let's try again...

**Review by Scottj1s — APPROVED** [review]

**Comment by kennykerr** [comment]
https://devblogs.microsoft.com/oldnewthing/20201112-00/?p=104444

**Pull request merged**
