### PR TITLE
Change to using the centrally shared copy of DevCheck (from eng\common)

### PR DESCRIPTION
**Pull request by DrusTheAxe**

### CODE REVIEW

**Comment by kythant** [comment]
Need to update yml to use the .cmd instead

**Comment by DrusTheAxe** [comment]
> Need to update yml to use the .cmd instead

Good catch! But nah, anyone using the .ps1 can just change the path. Only reason for the cmd is end user interactive convenience, the yml specify the .ps1 they can (and should) continue doing so

**Review by jonwis — APPROVED** [review]

**Pull request merged**
