### PR TITLE
Add <auto-generated> tag in C# files added to projects

### PR DESCRIPTION
**Pull request by DrusTheAxe**
Add <auto-generated> tag in C# files added to projects using WinAppSDK to prevent StyleCopy warnings developers can't do anything about. See https://github.com/microsoft/WindowsAppSDK/pull/2522 and https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1145#issuecomment-128672540 for more details

This is a modified form of https://github.com/microsoft/WindowsAppSDK/pull/2522 (some formatting and more accurate message) but I couldn't figure out how to make an update to that or otherwise update that branch (probably because it's not in this project) so I made this parallel PR to carry that work over the finish line.

### CODE REVIEW

**Comment by DrusTheAxe** [comment]
+@BenJKuhn @jlaanstra @riverar who'd created|commented on that other PR

**Review by BenJKuhn — APPROVED** [review]

**Comment by riverar** [comment]
Looks fine, thanks for heads up. 👍

**Comment by jlaanstra** [comment]
LGTM

**Pull request merged**
