### PR TITLE
Fix ".Experimental" VSIX renaming

### PR DESCRIPTION
**Pull request by DefaultRyan**
The newly-split Cpp and Cs VSIX projects now use `.Experimental` in the Id for experimental builds, but there was logic leftover from the old legacy VSIX that said `.Preview`.

### CODE REVIEW

**Review by rohanp-msft — APPROVED** [review]
:shipit:

**Comment by alwu-msft** [comment]
This is superseded by https://github.com/microsoft/WindowsAppSDK/pull/1341.

**Pull request merged**
