### PR TITLE
Add features by release into roadmap.md

### PR DESCRIPTION
**Pull request by soroshsabz**
ITNOA

I add some important features from planned tab in https://portal.productboard.com/winappsdk/1-windows-app-sdk/tabs/2-planned into your roadmap.

I think you have to update your roadmap periodically.

---

A microsoft employee must use /azp run to validate using the pipelines below.

WARNING:
Comments made by azure-pipelines bot maybe inaccurate. 
Please see pipeline link to verify that the build is being ran.

For status checks on the develop branch, please use TransportPackage-Foundation-PR
(https://microsoft.visualstudio.com/ProjectReunion/_build?definitionId=81063&_a=summary)
and run the build against your PR branch with the default parameters.

For status checks on the main branch, please use microsoft.ProjectReunion
(https://dev.azure.com/ms/ProjectReunion/_build?definitionId=391&_a=summary)
and run the build against your PR branch with the default parameters.

### CODE REVIEW

**Comment by soroshsabz** [comment]
related to https://github.com/microsoft/microsoft-ui-xaml/pull/8761

**Comment by soroshsabz** [comment]
@gabbybilka please review it

thanks

**Comment by soroshsabz** [comment]
related to https://github.com/microsoft/microsoft-ui-xaml/pull/8673

**Comment by gabbybilka** [comment]
@chigy FYI

**Comment by chigy** [comment]
@soroshsabz , thank you for your effort. However, we are working on the update to roadmap.md file so your change will not be needed.

**Pull request closed without merging**
