### PR TITLE
Update to use WindowsAppSDK-PublishSymbol-Steps.yml from WindowsAppSDK Config

### PR DESCRIPTION
**Pull request by kythant**
Use https://microsoft.visualstudio.com/ProjectReunion/_git/WindowsAppSDKConfig?path=/AzurePipelinesTemplates/WindowsAppSDK-PublishSymbol-Steps.yml

The old template relies on the use of eng\common\Scripts\PublishPublicSymbols.ps1 and eliminating this moves us towards our goal of eliminating the eng\common which is deprecated with us moving to dotnet's maestro

### CODE REVIEW

**Comment by kythant** [comment]
Testing in OneBranch builds here
https://microsoft.visualstudio.com/ProjectReunion/_build/results?buildId=104627359&view=results

**Review by alexlamtest — APPROVED** [review]

**Pull request merged**
