### PR TITLE
Update MRTCore ManagedTests to use TAEF and onboard it to Pipeline Tests

### PR DESCRIPTION
**Pull request by kythant**
Update MRTCore ManagedTests to use TAEF and onboard it to Pipeline Tests.

Also updated the MRT Core yml to not use the VSTest

### CODE REVIEW

**Review by alexlamtest — COMMENTED** [review]
How about removing the reference to this test from the .yml file that builds MRTCore?

**Comment by kythant** [comment]
> How about removing the reference to this test from the .yml file that builds MRTCore?

Oh yes I forgot about this.

**Review by alexlamtest — APPROVED** [review]

**Pull request merged**
