### PR TITLE
Update CsWinRT version to 2.0.3

### PR DESCRIPTION
**Pull request by manodasanW**
A microsoft employee must use /azp run to validate using the pipelines below.

WARNING:
Comments made by azure-pipelines bot maybe inaccurate. 
Please see pipeline link to verify that the build is being ran.

For status checks on the develop branch, please use TransportPackage-Foundation-PR
(https://microsoft.visualstudio.com/ProjectReunion/_build?definitionId=81063&_a=summary)
and run the build against your PR branch with the default parameters.

For status checks on the main branch, please use microsoft.ProjectReunion
(https://dev.azure.com/ms/ProjectReunion/_build?definitionId=391&_a=summary)
and run the build against your PR branch with the default parameters.

### CODE REVIEW

**Comment by hez2010** [comment]
Any chance to update to a release of CsWinRT that contains the fix https://github.com/microsoft/CsWinRT/pull/1340, so that NativeAOT can be unblocked?

**Comment by manodasanW** [comment]
> Any chance to update to a release of CsWinRT that contains the fix [microsoft/CsWinRT#1340](https://github.com/microsoft/CsWinRT/pull/1340), so that NativeAOT can be unblocked?

I believe that change should only affect the Windows SDK projection given it is the only projection with generic types.  Due to that, independent of the version used here in WinAppSDK, once I release a new CsWinRT and Windows SDK projection, folks should be able to get the changes.

**Comment by manodasanW** [comment]
> No commit pushedDate could be found for PR 3738 in repo microsoft/WindowsAppSDK

PR build was manually run and it succeeded (20230714.2).  Reporting seems to be not in sync due to manual run.

**Review by Scottj1s — APPROVED** [review]

**Pull request merged**
