### PR TITLE
Remove .NET installer script from repo (remove from Helix pipeline and MRT core pipeline)

### PR DESCRIPTION
**Pull request by jefgen**
The dotnet installer exe isn't necessary, as the .NET runtime bits are brought along with the `WindowsAppSDK.Helix.Test.NetCore` project in the test payload for Helix.

For MRT Core (per Hui): The runtime should be part of SDK, and in fact the SDK with correct version is already installed.

### CODE REVIEW

**Review by huichen123 — COMMENTED** [review]
since you are here, can you also remove one in build-mrt.yml as well?

**Comment by jefgen** [comment]
> since you are here, can you also remove one in build-mrt.yml as well?

Sure, I'll also remove the file from the repo too.

**Review by huichen123 — APPROVED** [review]

**Review by axelandrejs — APPROVED** [review]

**Pull request merged**
