### PR TITLE
Update bug template tag to 1.1.4

### PR DESCRIPTION
**Pull request by gabbybilka**

### CODE REVIEW

**Review by kythant — APPROVED** [review]

**Comment by Ksm9980** [comment]
can't debug on x64,unpackaged with <WindowsPackageType>None</WindowsPackageType> or   <WindowsAppSdkBootstrapInitialize>true</WindowsAppSdkBootstrapInitialize>
but,  x86,unpackaged is OK

**Comment by Ksm9980** [comment]
project : "WindowsPackageType" None  or "WindowsAppSdkBootstrapInitialize" true

**Comment by Ksm9980** [comment]
test1.png : x64 unpackaged (bug?), test2.png : x86 unpackage(OK)
test1
test2
d

**Pull request merged**
