### PR TITLE
Installation with System-Account doesn't work #2546

### LINKED ISSUE #2546: Installation with System-Account doesn't work
### Describe the bug

Trying to install Windows App SDK 1.0.3 with System-Account fails with 
```
Installing license: WAR_MAINPACKAGE_LICENSE
Install result : 0x0
Deploying package: Microsoft.WindowsAppRuntime.1.0_3.469.1654.0_x64__8wekyb3d8bbwe
Package deployment result : 0x80073cf9 Install failed. Please contact your software vendor.
One or more install operations failed. Result: 0x80073cf9
```

Installing WinAppSDK on the same machine (clean VM) works correctly when installing as admin user.

First reported here:
https://github.com/microsoft/PowerToys/issues/18065

### Steps to reproduce the bug

- Download WinAppSDK 1.0.3 x64 runtime installer https://aka.ms/windowsappsdk/1.0/1.0.3/windowsappruntimeinstall-1.0.3-x64.exe
- Open cmd.exe with psexec ` .\PsExec.exe -s -i cmd.exe`
- Try running WinAppSDK installer from opened cmd `WindowsAppRuntimeInstall.exe`
- Observe the output

### Expected behavior

WinAppSDK installs correctly without errors

### Screenshots

image

### NuGet package version

_No response_

### Packaging type

_No response_

### Windows version

Windows 10 version 21H1 (19043, May 2021 Update)

### IDE

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DrusTheAxe**
Per https://github.com/microsoft/WindowsAppSDK/issues/2546#issuecomment-1136746733

> If you're trying to install the runtime for use by the LocalSystem account then it won't work. The one user account Windows can't register MSIX packages for is LocalSystem so when the installer is running as LocalSystem and calls pkgmgr.AddPackageAsync() it will fail.
> 
> If you're trying to install the runtime for all users (i.e. provisioning packages) the installer's implementation doesn't handle it. It should work, so this would be a bug in the installer. As noted recently https://github.com/microsoft/WindowsAppSDK/discussions/2515#discussioncomment-2807160 the installer's core logic is effectively
> 
> ```
> FOREACH p IN *.msix
>     packagemanager.AddPackageAsync(p)
>     IF !p.IsFramework and IsElevated()
>         packagemanager.ProvisionPackagesForAllUsersAsync(p.packagefamilyname)
> ```
>
> This is implemented in installer\dev\install.cpp, notably lines 259 (AddPackage), 269-270 (IF...IsElevated) and 275 (ProvisionPackage). AddPackage will fail if running as LocalSystem. If the intent is to provision the package for all users and not register it for LocalSystem (as Windows doesn't support that), the logic needs a small but critical alteration:
>
> ``` 
> FOREACH p IN *.msix
>     IF GetTokenInformation(TOKEN_USER) == CreateWellKnownSid(WinLocalSystem)
>         packagemanager.StagePackageAsync(p)
>     ELSE
>         packagemanager.AddPackageAsync(p)
>     IF !p.IsFramework and IsElevated()
>         packagemanager.ProvisionPackagesForAllUsersAsync(p.packagefamilyname)
> ```

Change AddPackage() to AddOrStagePackage() and Stage if running as LocalSystem.

https://task.ms/39720940

closes #2546

### CODE REVIEW

**Comment by crutkas** [comment]
when this gets checked in, when would this flow out to end users?  1.2 release or would it be maybe a 1.1.X release time frame?

**Comment by DrusTheAxe** [comment]
> when this gets checked in, when would this flow out to end users? 1.2 release or would it be maybe a 1.1.X release time frame?

Yes :-)

It'll go into main which will be 1.2. As it's also of interest for 1.1 (I expect it'll meet the bar) this issue is tagged servicing-consider-1.1 (above).

Standard policy for servicing is make the change in main, run the proposed servicing change through shiproom review for approval then cherry-pick to to the release branch (in this case, `release/1.1-stable`) and it'll flow out with the next servicing update soon after.

**Review by sachintaMSFT — APPROVED** [review]

**Pull request merged**
