### PR TITLE
[MRTCore] Add Microsoft.Windows.Globalization.ApplicationLanguages class

### PR DESCRIPTION
**Pull request by kmahone**
A port of PR #4181

It looks like there are issues running the validation pipeline from forks, so porting the commits to a branch in this repo.

Changing the application language using [PrimaryLanguageOverride](https://learn.microsoft.com/uwp/api/windows.globalization.applicationlanguages.primarylanguageoverride) property from `Windows.Globalization.ApplicationLanguages` namespace is not supported for WindowsAppSDK unpackaged apps, only for packaged. To support language change for un-packaged applications `Microsoft.Windows.Globalization.ApplicationLanguages.ApplicationLanguages` type is introduced in MRTCore. `Microsoft.Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride` property is supported both for packaged and un-packaged WindowsAppSDK apps.

Sample app used to verify the change: https://github.com/stefansjfw/testwasdk/blob/master/testlocalwinappsdk/App.xaml.cs#L36

### CODE REVIEW

**Review by huichen123 — APPROVED** [review]

**Comment by ghost1372** [comment]
@kmahone tnx for this great api, can we use it with next release? (v1.6-exp2 ?)

**Comment by codendone** [comment]
@ghost1372 Yes, this API is in the [1.6.240701003-experimental2](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.6.240701003-experimental2) release.

**Pull request merged**
