### PR TITLE
Find/replace of copyright header strings with CELA guidance

### PR DESCRIPTION
**Pull request by EricJohnson327**

### CODE REVIEW

**Comment by riverar** [comment]
Highly recommend you return to CELA and inform them that this is a open source repository that takes in outside contributions and does not require the transfer of copyright from its external contributors. (This means they may not own the copyright on every single file in this repository.) They should then give you a new header that reflects that, similar to what was done on the .NET side.

Example:
```
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
```

Looping in @jeffwilcox for awareness. This seems to keep happening year over year... seems like CELA should be a bit more experienced with the OSS workflow by now.

**Comment by jeffwilcox** [comment]
Thanks @riverar 👏.

This does represent the latest guidance - our latest templates remove the "All rights reserved", and many of the companies we work with prefer this wording. I agree it's maybe a bit randomizing, but do support this update if it doesn't impact the rest of the project too much.

**Review by BenJKuhn — APPROVED** [review]

**Comment by riverar** [comment]
Always appreciate when no one acknowledges my concerns. It certainly demotivates me to continue contributing here.

**Comment by BenJKuhn** [comment]
Contributions into this repo are covered by the Contributor License Agreement that folks digitally sign to contribute to Microsoft repositories. This includes granting specific rights to Microsoft for contributed code. The copyright statement does not state or infer that Microsoft employees were the original author of all of the code. It does not imply that Microsoft is an _exclusive_ copyright holder (the CLA covers this as well). Nor does it limit the rights conferred under the MIT license that applies to use of code provided in this repository.

Is there a more specific concern that hasn't been addressed?

Ben

**Comment by BenJKuhn** [comment]
Also, you can see an example of the CLA here:

https://opensource.microsoft.com/pdf/microsoft-contribution-license-agreement.pdf

Thanks,

Ben

**Comment by riverar** [comment]
> The copyright statement does not state or infer that Microsoft employees were the original author of all of the code.

It is extremely frustrating that, instead of doing the right thing here (like the .NET folks did), we're going to instead play legal word games.

Thanks for closing the loop; please consider this matter closed.

**Pull request merged**
