### PR TITLE
Optimize loose PNG assets

### PR DESCRIPTION
**Pull request by riverar**
Reduces footprint by ~253.19 KiB. Does not include PNGs in icons or libraries. Does not affect PNG visual appearance in any way.

### CODE REVIEW

**Comment by DrusTheAxe** [comment]
Neat. How'd you 'squeeze' those files?

**Comment by riverar** [comment]
@DrusTheAxe PngDistill distributed with Fiddler; Powershell: `ls *.png -recurse | % { ./pngdistill.exe $_ REPLACE }`. Ideally assets would be checked at PR time and fail if chunky but we're not there yet.

Related: #523 #532

**Review by andrewleader — APPROVED** [review]

**Comment by riverar** [comment]
@andrewleader Bump

**Comment by DrusTheAxe** [comment]
> @DrusTheAxe Howard Kapustein FTE PngDistill distributed with Fiddler; Powershell: `ls *.png -recurse | % { ./pngdistill.exe $_ REPLACE }`. Ideally assets would be checked at PR time and fail if chunky but we're not there yet.
> 
> Related: #523 #532

@BenJKuhn do we have a task to automate this? Would be nice to run pngdistill on every image on checkin (if it's safe, and seems to be)

**Comment by DrusTheAxe** [comment]
> Is there anything for me to do here? This PR is getting long in the tooth. CI isn't going to validate anything here...

I'm puzzled. I think the build fails because there was a problem with main at time of the last merge, but I don't see an 'update branch' button. Hmmm. riverar:...? This is a fork? I think if riverar:user/riverar/png-squeeze-pass-3 is updated with the latest in main the checkin-build will be happy and it'll checkin. But I don't know how to get it there. Do you?

(I haven't done any github cross-fork checkins before)

**Comment by riverar** [comment]
@DrusTheAxe Should be good now, not sure if you have to manually push a button somewhere to kick off a new build.

**Comment by DrusTheAxe** [comment]
> not sure if you have to manually push a button somewhere to kick off a new build.

I do (or another Microsofty)

Anyone can make PRs but builds can only be initiated by Microsoft folks
(due to the bitcoin-mining-'free'-compute-resources hacks the industry saw some months back)

Kicked off. If it hits another bump ping me and I can take a look and we'll figure it out

And thanks again for doing this :-)

**Comment by riverar** [comment]
@DrusTheAxe Guessing those failures are unrelated (I don't have access to the logs).

**Comment by DrusTheAxe** [comment]
> @DrusTheAxe Howard Kapustein FTE Guessing those failures are unrelated (I don't have access to the logs).

Yeah they're unrelated. Something's up in the test plumbing, but even though this isn't causing that that's still blocking this. I'm not sure why.

main is currently locked but it should open soon. Once it does I'll try the /azp run trick again. If that's still a problem I can try making a fork of your branch, rebased off main and as a new PR and see if that fares any better.

**Comment by DrusTheAxe** [comment]
@riverar there was a (serious) problem with the test environment machinery that's been corrected. Can you sync to the latest and we can try one more time. If we still have problems I'll make a new PR with your changes and see if that gets around the problem. Thanks

**Comment by riverar** [comment]
@DrusTheAxe Loading the catapult, standby.

**Comment by riverar** [comment]
@DrusTheAxe Ready for you to press a button. (We should really configure the repo to require first-time-only approval, not this manual explicit button press. What I proposed is how all the other Microsoft repos work.)

**Comment by andrewleader** [comment]
I noticed we never merged this, seems like it's all working now? Should we merge @DrusTheAxe? Kicking off another run...

/azp run

**Comment by DrusTheAxe** [comment]
Hey! I'd forgotten about this. Looks like the past build oddities are past. Aaand we're in!

Thanks Rafael

**Comment by kinkycat91** [comment]
H

**Pull request merged**
