### PR TITLE
Add <auto-generated> tag in C# files added to projects #2533 (servicing 1.1)

### PR DESCRIPTION
**Pull request by DrusTheAxe**
cherry-pick of [Add <auto-generated> tag in C# files added to projects #2533](https://github.com/microsoft/WindowsAppSDK/pull/2533) for 1.1-servicing

https://task.ms/39861117

See [StyleCop warns about a .cs file coming from the WinAppSDK 1.1 NuGet Package](https://github.com/microsoft/TemplateStudio/issues/4526#)
#4526 for more info

### CODE REVIEW

**Review by mikebattista — APPROVED** [review]

**Review by sachintaMSFT — APPROVED** [review]

**Comment by DrusTheAxe** [comment]
Build failure due to timeout in the pipeline's task "Run tests in Helix"...for a PR that just changes some comments? Argh!

Let's try again...

**Pull request merged**
