### PR TITLE
Creating AppAttach folder

### PR DESCRIPTION
**Pull request by rahul89dadhich**
A microsoft employee must use /azp run to validate using the pipelines below.

WARNING:
Comments made by azure-pipelines bot maybe inaccurate. 
Please see pipeline link to verify that the build is being ran.

For status checks on the develop branch, please use TransportPackage-Foundation-PR
(https://microsoft.visualstudio.com/ProjectReunion/_build?definitionId=81063&_a=summary)
and run the build against your PR branch with the default parameters.

For status checks on the main branch, please use microsoft.ProjectReunion
(https://dev.azure.com/ms/ProjectReunion/_build?definitionId=391&_a=summary)
and run the build against your PR branch with the default parameters.

### CODE REVIEW

**Comment by DrusTheAxe** [comment]
I don't understand. This looks relatively boilerplate, and I don't see any existing dev\AppAttach directory this would be commenting on so I'm stumped -- what's the goal of this PR?

**Review by DrusTheAxe — CHANGES_REQUESTED** [review]
What's the goal of this PR?

**Comment by rahul89dadhich** [comment]
> What's the goal of this PR?

This is placeholder where we will be adding changes for app attach lib and extension, created it to get confirmation if we are putting code at right place also we are merging it to user branch.
Hope that clarifies the question.

**Comment by DrusTheAxe** [comment]
> > What's the goal of this PR?
> 
> This is placeholder where we will be adding changes for app attach lib and extension, created it to get confirmation if we are putting code at right place also we are merging it to user branch. Hope that clarifies the question.

Ahhh. In that case...

1. **It MAY be the right place**. Depends on the actual content you're adding
  1. General guidance is dev/<topic> and matching test/<topic> where topic is usually a subsystem. It _can_ be feature, but 'feature'/scenario tends to map poorly to code artifacts (many scenarios can need 1 component and 1 scenario can need many components). 
3. If you're unsure please ask.
4. [dev/Coding-Guidelines.md](https://github.com/microsoft/WindowsAppSDK/blob/main/docs/Coding-Guidelines.md) is intended to be doc the prereqs, rules and softer common guidelines and (if you will) stylistic aspects of developing in WinAppSDK. But it's a perpetual work in progress (like many such docs) and doesn't have guidance on your question - but it should. I've taken a note to see that gets beefed up for future reference :-)
5. If it's kinda clear to you go ahead and make a PR. If you guess right then awesome. And if you guessed wrong, PR feedback will suggest renaming or moving content around. NOTE: Even PRs by experienced folks sometimes have that feedback. Semi-common occurrence as folks point out ways to better structure and manage the project. Development is a team sport :-)

As the PR has no meaningful content and was really a way to ask about source structure I suggest abandoning the PR.

~If~ When :-)  you have content throw up a PR for review. Or even a draft PR if you have questions and seeing the code helps express and/or answer them. All good.

**Comment by rahul89dadhich** [comment]
> 2\. matching test/

Make sense, we will go through the guideline and will adhere to the same.
Closing this PR as of now, will re-raise with the changes in coming week and will add you as reviewer.

Thank you :)

**Pull request closed without merging**
